language: node_js
node_js:
  - "5"
script: gulp build
branches:
 only:
    - deploy
deploy:
  provider: heroku
  api_key: "09YR5aW9ZF64/MFKKk6Oo3lZKpIF1Ik44HvzLi9yo/E5TOuTMBHW3C5lEJtGtH4rdsrOgrebA5jJdZmghJYc4KU5I2h+rvFrOfBbGd3T26fSOU83vNedYIE9DtkscmH2yiyFeYnBm2L4DMUgQ9Nszs3KVFD13Q/0pDEp1THw2xk6E9o/EkxKgzZ75A4YopLJVS4qltWtw6pwA0eiAUwI6Cz/iazh6K78h7xg6W1h2uHMrgIo+mLF78IEaHjFnGSAPeys5AXk3cozDH7/ovSNEhn2Iye2FmYan+jqj5yUv78vufBOGuJm3IXbFlAETBwT+iem2veWYHVMTk5qT8RFrD3+6FUZopExx/eHJtkCDwaazyX3UAN+EKtK/B3r+Pb1wXNgjp33H46beJfaqSGxnFSbXPpbwDo+JhbKw//ps+ro/O9puTVcE3jjqcfQ2jRIS4pi2qO8CC3gMKiU/pxxZp3cvwRZudaJpzvPcVLp1zsr8O7ek9mvSWZ6bci6RpsnfUv/saBciScol5sX6z+E7jmsk8E7ALRdoVokT0K2YN9g0SLMzpgqwoW8ssNmTMMPektdNw6lhmwN5uKsrW+S+tGr2TP+/xVny+riUfEEaBP0aOp5bw6mK9tJ/d+X6mq2KjXaFWXvsBQhluZ+hozYfZcxwLQjPkf5kv+2BkFEThQ="
  on: deploy